const skills = [
    {
        skillCategory: "general",
        characteristicUsed: "INT",
        skillName: "Alchemy",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "general",
        characteristicUsed: "INT",
        skillName: "Astrocartography",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "general",
        characteristicUsed: "BR",
        skillName: "Athletics",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "general",
        characteristicUsed: "INT",
        skillName: "Computers",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "general",
        characteristicUsed: "PR",
        skillName: "Cool",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "general",
        characteristicUsed: "AG",
        skillName: "Coordination",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "general",
        characteristicUsed: "WILL",
        skillName: "Discipline",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "general",
        characteristicUsed: "AG",
        skillName: "Driving",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "general",
        characteristicUsed: "INT",
        skillName: "Mechanics",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "general",
        characteristicUsed: "INT",
        skillName: "Medicine",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "general",
        characteristicUsed: "INT",
        skillName: "Operating",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "general",
        characteristicUsed: "CUN",
        skillName: "Perception",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "general",
        characteristicUsed: "AG",
        skillName: "Piloting",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "general",
        characteristicUsed: "BR",
        skillName: "Resilience",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "general",
        characteristicUsed: "AG",
        skillName: "Riding",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "general",
        characteristicUsed: "CUN",
        skillName: "Skulduggery",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "general",
        characteristicUsed: "IAGNT",
        skillName: "Stealth",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "general",
        characteristicUsed: "CUN",
        skillName: "Streetwise",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "general",
        characteristicUsed: "CUN",
        skillName: "Survival",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "general",
        characteristicUsed: "WILL",
        skillName: "Vigilance",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "magic",
        characteristicUsed: "INT",
        skillName: "Arcana",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "magic",
        characteristicUsed: "WILL",
        skillName: "Divine",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "magic",
        characteristicUsed: "CUN",
        skillName: "Primal",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "combat",
        characteristicUsed: "BR",
        skillName: "Brawl",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "combat",
        characteristicUsed: "AG",
        skillName: "Gunnery",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "combat",
        characteristicUsed: "BR",
        skillName: "Melee",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "combat",
        characteristicUsed: "BR",
        skillName: "Melee-Light",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "combat",
        characteristicUsed: "BR",
        skillName: "Melee-Heavy",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "combat",
        characteristicUsed: "AG",
        skillName: "Ranged",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "combat",
        characteristicUsed: "AG",
        skillName: "Ranged-Heavy",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "combat",
        characteristicUsed: "AG",
        skillName: "Ranged-Light",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "social",
        characteristicUsed: "PR",
        skillName: "Charm",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "social",
        characteristicUsed: "WILL",
        skillName: "Coercion",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "social",
        characteristicUsed: "CUN",
        skillName: "Deception",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "social",
        characteristicUsed: "PR",
        skillName: "Leadership",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "social",
        characteristicUsed: "PR",
        skillName: "Negotiation",
        isCareer: false,
        rank: 0,
    },
    {
        skillCategory: "knowledge",
        characteristicUsed: "INT",
        skillName: "Knowledge",
        isCareer: false,
        rank: 0,
    }
]

